apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontend-tier
  labels:
    tier: fontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/iotmaulana/karsajobs-ui:latest
        env:
          # to connect with BackEnd app (karsajobs)
          - name: VUE_APP_BACKEND
            value: http://$(BACKEND_TIER_SERVICE_HOST):$(BACKEND_TIER_SERVICE_PORT_APP)

        # expose port 8000
        ports:
          - containerPort: 8000
