apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-tier
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      # backend pod karsajob
      - name: backend
        image: ghcr.io/iotmaulana/karsajobs:latest

        #expose container on port 8080
        ports:
          - containerPort: 8080

        env:
        # backend app port
        - name: APP_PORT
          value: "8080"

        # mongodb database port
        - name: MONGO_HOST
          value: mongodb://$(MONGO_SERVICE_HOST):$(MONGO_SERVICE_PORT_DATABASE)

          # mongodb database username
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: MONGO_ROOT_USERNAME

          # mongodb database password
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: MONGO_ROOT_PASSWORD
