apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
    tier: database
  ports:
    - port: 27017
      protocol: TCP
      name: database
  clusterIP: None
