apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: database
  serviceName: mongo
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: mongo
        tier: database
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - image: mongo:latest
        name: mongo

        # mongod config
        command:
          - mongod
          - --config
          - /config/mongodb.conf

        # expose port 27017
        ports:
          - containerPort: 27017

        # configuring database credentials
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD

        # mount volumes
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db

        - name: config
          mountPath: /config

        - name: credentials
          mountPath: /etc/mongo-credentials

      # claim volumes
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim

      - name: config
        configMap:
            name: mongo-config
            items:
            - key: mongo.conf
              path: mongodb.conf

      - name: credentials
        secret:
          secretName: mongo-credentials
